### ISSUE TITLE
Autogenerate cffi module?

### ISSUE THREAD

**Issue by Korijn** [pygfx/wgpu-py#160]
https://github.com/PyO3/maturin/
https://github.com/getsentry/milksnake

Maybe I'm mistaken but it looks like you can automatically generate a python cffi module based on the header and binaries we have... is that useful?

**Comment by almarklein** [comment]
From what I understand about Milksnake, it could ease the distribution process, e.g. take care of the wheel tagging that we do with auditwheel. Although we don't build the binaries, but download them - not sure if we could still take advantage of Milkshake in this case, but it could be worth a try.

Milkshake's readme says: "_[...] native libraries that are then loaded with CFFI at runtime._" That's what we do as well: we feed cffi the headerfile and it will generate constants and create the function bindings with correct types etc. (something that had to be written out in code when just using ctypes).

The code in `rs.py` is mostly about mapping the WebGPU API to the wgpu-native C API, a large part of which is creating C structs from Python dicts and then calling the appropriate C function. This is not something these tools can help with. In fact, I think any code that would automate this process would become more complex than writing it by hand because of the many subtleties that change all the time.

From what I understand from tools like PyO3 and Maturin, they would help if we were targeting a Rust library, by automatically creating the C-API, header files, and then loading it up with cffi. But we're targeting a C API that happens to be implemented in Rust. Though in theory we could target wgpu-core, I guess.

I might be missing something though, so happy to discuss this further :)

**Comment by Korijn** [comment]
It took me some time to understand this fully, sorry about the confusion. :) Thanks for clarifying; what didn't fully click in my brain is the runtime aspect of cffi. You are right, we are already kind of doing exactly what milkshake and maturin do, except that the rust build and cbindgen process is already executed upstream, and we just hook up cffi.

**Comment by almarklein** [comment]
I also had to think very carefully how everything relates :)
