### ISSUE TITLE
Depth buffer access

### ISSUE THREAD

**Issue by mllobera** [pygfx/wgpu-py#285]
Following this [conversation](https://github.com/pygfx/pygfx/discussions/318#discussioncomment-3312809). Would it be worth proposing a function that would allow more direct access to the depth buffer?

**Comment by almarklein** [comment]
Reading from the depth buffer is not a problem from wgpu-py. The problem is with how pygfx works: there are multiple render passes, and the depth buffer is re-used in these passes, so its content is probably not what you're interested in. One solution is to use multiple depth buffers, but this costs a lot of memory.

**Comment by Korijn** [comment]
See here: https://github.com/pygfx/wgpu-py/tree/main/examples
