### ISSUE TITLE
Crash in lib.wgpuSurfaceGetSupportedFormats call

### ISSUE THREAD

**Issue by berendkleinhaneveld** [pygfx/wgpu-py#341]
The call to lib.wgpuSurfaceGetSupportedFormats() in rs.py:557 crashes when trying to create a canvas on a remote windows machine. Happens with version 0.9.1, Vulkan backend.

```
thread '<unnamed>' panicked at 'not yet implemented', src\conv.rs:667:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The full stack trace doesn't seem to reveal anything significant.

**Comment by almarklein** [comment]
What I think happens is that wgpu-native does a call to wgpu-core to get the supported formats, which gives a list of texture formats as wgpu-core enums. These enums are converted to webgpu enums (from webgpu.h). But there are texture formats that exist in wgpu-core that do not (yet?) exist in webgpu.h, and this is the error you get in `conv.rs` shown in the error log.

This is the relevant code in https://github.com/gfx-rs/wgpu-native/blob/v0.14.2.3/src/lib.rs

<img width="968" alt="image" src="https://user-images.githubusercontent.com/3015475/219480462-81ce32ac-65c5-4428-89cb-9702c37937f1.png">

This has, however, been fixed in recent changes:

<img width="751" alt="image" src="https://user-images.githubusercontent.com/3015475/219480899-dbaee486-2f4b-4a5f-a371-0a798b84d45c.png">
