### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by tf4ong** [pygfx/wgpu-py#349]
Hi,

I have been try to install wgpu on raspberry pi bullseye but it keeps on giving me an error. 

Runtimeerror:could not ding WGPU library in /home/pi/.local /lib/python3/site-packages/wgpu/resource/libwgpu_native -release.so

**Comment by almarklein** [comment]
Raspberry pi is not yet supported, we track this in #187.

Currently, everything is in place to support raspberry pi from our side, but [wgpu-native](https://github.com/gfx-rs/wgpu-native) does not work yet, because of the glibc library (see https://github.com/gfx-rs/wgpu-native/pull/148#issuecomment-1404917031).

**Comment by almarklein** [comment]
Binaries are available here: https://github.com/gfx-rs/wgpu-native/releases/tag/v0.14.2.3
