### ISSUE TITLE
Sync events with draws

### ISSUE THREAD

**Issue by almarklein** [pygfx/wgpu-py#355]
@korijn mentioned in a comment in a pygfx, that  game engines usually run a tight loops with the following steps:

   1. Query input device state (joysticks, buttons, mice, etc)
   2. Update world state
   3. Render frame
 
That got me thinking. Right now, when a mouse event happens, this causes certain state to be changed. If two (or more) such events happen in between two draws, the state is updated twice, but we only see the final state.

We already do some event throttling to reduce this, but we could also aggregate the events and only dispatch them right before doing the draw, which could potentially result in more performance because it avoids calculating stuff that is never shown anyway.

One problem with this is that right now, if nothing changes, there are also no new draws, which is nice to avoid depleting your battery, and safes network traffic when using the notebook. We'd have to dispatch the events on a regular interval. I'm not sure what happens if we ask the GUI to schedule a draw and then not draw it.

Any other caveats?

**Comment by Korijn** [comment]
Responding to your question:

In pygame, and I think Unity and other engines do this as well, events from the OS are stored in a queue-like buffer as they come in.

Then, the first thing that happens in the game loop, is that a copy of the buffer is retrieved and the original buffer is emptied. The events on the copy are processed, and then the next frame is drawn. Meanwhile new events coming in go into the fresh buffer.

You could perform event aggregation on the buffer copy before it is processed to reduce the amount of events.

---

Independently thought:

I think this tight loop pattern is something users should be able to implement on top of pygfx, since it is mostly useful for game-like applications which have animation, sound, physics and AI going on constantly as well. It's almost a guarantee that you have to process events and render new frames on a regular/fixed rate.

For plotting and viz type applications it's much less useful. You only want to draw when it is needed. So now, when is the right time to buffer and aggregate? I guess you could say that you target a "max fps" and therefore when a first event comes in, you can set a timer to decide when the buffer should be processed.

For unlimited fps, you could disable buffering I guess.

**Comment by Korijn** [comment]
Also see https://github.com/pygfx/pygfx/issues/495

**Comment by almarklein** [comment]
Implemented in rendercanvas.
