### ISSUE TITLE
Invalid values/overflow when running in github CI

### ISSUE THREAD

**Issue by dc-dc-dc** [pygfx/wgpu-py#362]
I integrated this project into a machine learning framework to add support for webgpu. So far its been good and we can run most of the test suite locally using the library but when we go to CI we get strange errors on some operations.

Currently only utilizing the compute portion of the library, no rendering at all so don't believe the issue revolves around a missing package

Utilizing the github runner `windows-latest` as it seemed to be the most stable but still failing on some tests. These tests run fine locally and I have tested on multiple machines, only when utilizing github runners do they present themselves. We have other runtimes that run the same tests in CI that don't get these errors (CLANG, METAL, OPENCL) so I don't think its the actual values being passed that causes it. 

Output from CI runner:
```
============================== warnings summary ===============================
 D:\a\tinygrad\tinygrad\tinygrad\ops.py:100: RuntimeWarning: invalid value encountered in divide
 D:\a\tinygrad\tinygrad\tinygrad\ops.py:100: RuntimeWarning: overflow encountered in exp2
 D:\a\tinygrad\tinygrad\tinygrad\ops.py:100: RuntimeWarning: invalid value encountered in log2
 ```

**Comment by almarklein** [comment]
Running on CI does indeed come with some risk, because of the virtualization. We only run gpu stuff on Linux runners using Lavapipe, see e.g. [these docs](https://wgpu-py.readthedocs.io/en/stable/start.html#installing-lavapipe-on-linux).

On Windows, wgpu-py still defaults to Vulkan. My advice would be to try setting `WGPU_BACKEND_TYPE` (valid values are “Vulkan”, “Metal”, “D3D12”, “D3D11”, or “OpenGL”, though on Windows I'd only try Vulkan, D3D11 and D3D12). Try locally to see if the error can perhaps be reproduced, and on CI whether it can fix it :)

**Comment by dc-dc-dc** [comment]
Switching to a macos runner and forcing the metal backend worked for our CI needs. was also able to create a web demo running efficientnet if you want to check it out [here](https://cruzio.dev/posts/leveling-up-browser-with-webgpu/)

Thanks this library was a huge help!

**Comment by almarklein** [comment]
> Switching to a macos runner and forcing the metal backend

Out of interest, is that a runner with real hardware, or does it include virtualization for Metal somehow? 

> was also able to create a web demo running efficientnet if you want to check it out [here](https://cruzio.dev/posts/leveling-up-browser-with-webgpu/)

Very nice! Great to see wgpu-py also being used for compute tasks! Are you using the wgpu API directly, or do you make use of the `compute_with_buffers` util?
