### ISSUE TITLE
Add convenience function `enumerate_adapters`

### ISSUE THREAD

**Issue by skoudoro** [pygfx/wgpu-py#409]
Hi wgpu-py Team,

I can not find `enumerate_adapters()` to just get an idea of all gpu available in a machine. 

is there an alternative way to do that and this is something to add?

Thank you for the feedback.

**Comment by almarklein** [comment]
The wgpy-native implementation: https://github.com/gfx-rs/wgpu-native/blob/cf02ef3a28c92340483a0393505717bc66103d18/ffi/wgpu.h#L226

Good point. We could add it.

The function is not part of the WebGPU spec, but an extra convenience function by wgpu-native. That's why the code-generation has not told us to add it yet. Will update the title of this issue accordingly.

**Comment by Korijn** [comment]
Could this be just to provide something like a dropdown to select an adapter?

**Comment by skoudoro** [comment]
> Could this be just to provide something like a dropdown to select an adapter? What's the purpose?

I use only the compute shader for scientific computation purpose (no visualization needed for now). I would like to select a specific GPU for that.

Thank you all for the feedback

**Comment by toloudis** [comment]
I also have this use case working with scientific data where it would be beneficial to be able to partition work across multiple GPUs on one system, or let user make an informed choice of which GPU is more powerful.
