### ISSUE TITLE
codegen failing with ruff

### ISSUE THREAD

**Issue by fyellin** [pygfx/wgpu-py#632]
I take the current _api.py in the main branch and make the following two changes:

Line 23:  Add `, NoReturn` to the list of things imported from `typing`

Line 2465: At the end of `GPUBindingCommandsMixin` I add new the method:

```
    def _not_implemented(self, name) -> NoReturn:
        raise RuntimeError(f"{name} not implemented for {type(self).__name__}")
```

I now run `python codegen`.  You will get an error. It seems that the above line and the following `class GPUDebugCommandsMixin` line get mushed into a single line, and that a call to `ruff` to format the code complains about illegal Python.

At first I thought that the bug was that `Patcher._init(self, code)` shouldn't be calling `format_code` with the singleline argument set to `True`.  But when I set this to False, I start getting completely different errors.  It seems that there are times this needs to be True and times this needs to be False.  Or why is Patcher calling ruff in the first place when it is just starting?

There are some design decisions here I don't quite understand.

    `

**Comment by almarklein** [comment]
Right, the end of a signature is detected with `line.endswith("):")` so that's not going to work with these type annotations 😉 

I created a pr to fix it.

>  It seems that there are times this needs to be True and times this needs to be False.

It only needs to be true if the code that works with the result needs the signatures to be a on a single line. The patcher classes want this, because it makes it *much* easier to detect whether a signature has changed.
